### ISSUE TITLE
Fix vulnerability

### ISSUE THREAD

**Issue by BobWall23** [IronCoreLabs/FutureJS#12]
GitHub is reporting a high severity vulnerability CVE2019-10747 in `set-value`.

**Comment by ernieturner** [comment]
The `set-value` dependency can't be easily remedied. The version of `set-value` is like 4 levels of dependencies deep, all in Jest code. It appears that this will all be fixed when [Jest v25](https://github.com/facebook/jest/milestone/9) comes out, but no idea when that'll happen. So I'm closing this for now.
