### ISSUE TITLE
Feature: Add Object support for `Future.all`

### ISSUE THREAD

**Issue by justsml** [IronCoreLabs/FutureJS#4]
I love this library! 

I was wondering if y'all were open to an API addition to support Objects with `Future.all(<array>)`?

Similar to the `.all()` function in my FP library: https://www.fpromises.io/#fp-all

Thanks @madison-kerndt for kindly sharing this with me!

**Comment by ernieturner** [comment]
Great suggestion! This seems like a pretty reasonable thing to add, I should have time next week to work on it. Thanks for the input!

**Comment by justsml** [comment]
@ernieturner let me know if you want me to take a stab at it... ❤️ Or want the link to my implementation 😸

**Comment by ernieturner** [comment]
Supported added via https://github.com/IronCoreLabs/FutureJS/pull/5
